import type { Voice } from "./types"

/**
 * Snapshot of ElevenLabs premade voices (from the public /v1/voices endpoint).
 * Temporary seed data until our own API is wired up — see fetchVoices() in ./api.ts.
 */
export const ELEVENLABS_VOICES: Voice[] = [
  {
    id: "CwhRBWXzGAHq8TQ4Fs17",
    name: "Roger",
    tagline: "Laid-Back, Casual, Resonant",
    description: "Easy going and perfect for casual conversations.",
    gender: "male",
    age: "middle aged",
    accent: "american",
    useCase: "conversational",
    descriptive: "classy",
  },
  {
    id: "EXAVITQu4vr4xnSDxMaL",
    name: "Sarah",
    tagline: "Mature, Reassuring, Confident",
    description: "Young adult woman with a confident and warm, mature quality and a reassuring, professional tone.",
    gender: "female",
    age: "young",
    accent: "american",
    useCase: "entertainment tv",
    descriptive: "professional",
  },
  {
    id: "FGY2WhTYpPnrIDTdsKH5",
    name: "Laura",
    tagline: "Enthusiast, Quirky Attitude",
    description: "This young adult female voice delivers sunny enthusiasm with a quirky attitude.",
    gender: "female",
    age: "young",
    accent: "american",
    useCase: "social media",
    descriptive: "sassy",
  },
  {
    id: "IKne3meq5aSn9XLyUdCD",
    name: "Charlie",
    tagline: "Deep, Confident, Energetic",
    description: "A young Australian male with a confident and energetic voice.",
    gender: "male",
    age: "young",
    accent: "australian",
    useCase: "conversational",
    descriptive: "hyped",
  },
  {
    id: "JBFqnCBsd6RMkjVDRZzb",
    name: "George",
    tagline: "Warm, Captivating Storyteller",
    description: "Warm resonance that instantly captivates listeners.",
    gender: "male",
    age: "middle aged",
    accent: "british",
    useCase: "narrative story",
    descriptive: "mature",
  },
  {
    id: "N2lVS1w4EtoT3dr4eOWO",
    name: "Callum",
    tagline: "Husky Trickster",
    description: "Deceptively gravelly, yet unsettling edge.",
    gender: "male",
    age: "middle aged",
    accent: "american",
    useCase: "characters animation",
    descriptive: "",
  },
  {
    id: "SAz9YHcvj6GT2YYXdXww",
    name: "River",
    tagline: "Relaxed, Neutral, Informative",
    description: "A relaxed, neutral voice ready for narrations or conversational projects.",
    gender: "neutral",
    age: "middle aged",
    accent: "american",
    useCase: "conversational",
    descriptive: "calm",
  },
  {
    id: "SOYHLrjzK2X1ezoPC6cr",
    name: "Harry",
    tagline: "Fierce Warrior",
    description: "An animated warrior ready to charge forward.",
    gender: "male",
    age: "young",
    accent: "american",
    useCase: "characters animation",
    descriptive: "rough",
  },
  {
    id: "TX3LPaxmHKxFdv7VOQHJ",
    name: "Liam",
    tagline: "Energetic, Social Media Creator",
    description: "A young adult with energy and warmth - suitable for reels and shorts.",
    gender: "male",
    age: "young",
    accent: "american",
    useCase: "social media",
    descriptive: "confident",
  },
  {
    id: "Xb7hH8MSUJpSbSDYk0k2",
    name: "Alice",
    tagline: "Clear, Engaging Educator",
    description: "Clear and engaging, friendly woman with a British accent suitable for e-learning.",
    gender: "female",
    age: "middle aged",
    accent: "british",
    useCase: "informative educational",
    descriptive: "professional",
  },
  {
    id: "XrExE9yKIg1WjnnlVkGX",
    name: "Matilda",
    tagline: "Knowledgable, Professional",
    description: "A professional woman with a pleasing alto pitch. Suitable for many use cases.",
    gender: "female",
    age: "middle aged",
    accent: "american",
    useCase: "informative educational",
    descriptive: "upbeat",
  },
  {
    id: "bIHbv24MWmeRgasZH58o",
    name: "Will",
    tagline: "Relaxed Optimist",
    description: "Conversational and laid back.",
    gender: "male",
    age: "young",
    accent: "american",
    useCase: "conversational",
    descriptive: "chill",
  },
  {
    id: "cgSgspJ2msm6clMCkdW9",
    name: "Jessica",
    tagline: "Playful, Bright, Warm",
    description: "Young and popular, this playful American female voice is perfect for trendy content.",
    gender: "female",
    age: "young",
    accent: "american",
    useCase: "conversational",
    descriptive: "cute",
  },
  {
    id: "cjVigY5qzO86Huf0OWal",
    name: "Eric",
    tagline: "Smooth, Trustworthy",
    description: "A smooth tenor pitch from a man in his 40s - perfect for agentic use cases.",
    gender: "male",
    age: "middle aged",
    accent: "american",
    useCase: "conversational",
    descriptive: "classy",
  },
  {
    id: "hpp4J3VqNfWAUOO0d1Us",
    name: "Bella",
    tagline: "Professional, Bright, Warm",
    description: "This voice is warm, bright, and professional, characterized by a Standard American accent and a polished, narrative quality. It features a medium-high pitch with crisp diction and a deliberate, rhythmic pace that makes it highly intelligible and engaging for long-form listening.",
    gender: "female",
    age: "middle aged",
    accent: "american",
    useCase: "informative educational",
    descriptive: "professional",
  },
  {
    id: "iP95p4xoKVk53GoZ742B",
    name: "Chris",
    tagline: "Charming, Down-to-Earth",
    description: "Natural and real, this down-to-earth voice is great across many use-cases.",
    gender: "male",
    age: "middle aged",
    accent: "american",
    useCase: "conversational",
    descriptive: "casual",
  },
  {
    id: "nPczCjzI2devNBz1zQrb",
    name: "Brian",
    tagline: "Deep, Resonant and Comforting",
    description: "Middle-aged man with a resonant and comforting tone. Great for narrations and advertisements.",
    gender: "male",
    age: "middle aged",
    accent: "american",
    useCase: "social media",
    descriptive: "classy",
  },
  {
    id: "onwK4e9ZLuTAKqWW03F9",
    name: "Daniel",
    tagline: "Steady Broadcaster",
    description: "A strong voice perfect for delivering a professional broadcast or news story.",
    gender: "male",
    age: "middle aged",
    accent: "british",
    useCase: "informative educational",
    descriptive: "formal",
  },
  {
    id: "pFZP5JQG7iQjIQuC4Bku",
    name: "Lily",
    tagline: "Velvety Actress",
    description: "Velvety British female voice delivers news and narrations with warmth and clarity.",
    gender: "female",
    age: "middle aged",
    accent: "british",
    useCase: "informative educational",
    descriptive: "confident",
  },
  {
    id: "pNInz6obpgDQGcFmaJgB",
    name: "Adam",
    tagline: "Dominant, Firm",
    description: "A bright tenor pitch that immediately cuts through. The delivery is brash and openly confident, speaking with unwavering certainty and a slightly aggressive self-assurance.",
    gender: "male",
    age: "middle aged",
    accent: "american",
    useCase: "social media",
    descriptive: "",
  },
  {
    id: "pqHfZKP75CvOlQylNhV4",
    name: "Bill",
    tagline: "Wise, Mature, Balanced",
    description: "Friendly and comforting voice ready to narrate your stories.",
    gender: "male",
    age: "old",
    accent: "american",
    useCase: "advertisement",
    descriptive: "crisp",
  },
]
